version: "3"

services:
  postgresql:
    image: postgres:13
    container_name: "postgres-for-secure-coding"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: posgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
        - "25432:5432"

volumes:
  database:
    driver: local